-- DRAFT: separate Lumen database only. Not picked up by the ERP sql/ installer.
-- Review/execute using a migration account, never the Lumen runtime identity.
-- No ERP import, implicit actor creation, existing-table reuse, or DROP.
IF COALESCE(CAST(SESSION_CONTEXT(N'LumenPreferencesMigration') AS NVARCHAR(100)), N'') <> N'reviewed-separate-db'
    THROW 51000, 'Explicit reviewed separate database context required.', 1;
IF DB_NAME() IN ('master', 'model', 'msdb', 'tempdb')
    THROW 51001, 'System database rejected.', 1;
SET XACT_ABORT ON;
BEGIN TRY
BEGIN TRANSACTION;
CREATE TABLE dbo.LUMEN_ACTOR_LINK (
    CONNECTION_KEY VARCHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    FIRMA SMALLINT NOT NULL CHECK (FIRMA BETWEEN 1 AND 999),
    LOGO_PERSONEL INT NOT NULL CHECK (LOGO_PERSONEL > 0),
    ACTOR_ID UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_LUMEN_ACTOR_LINK PRIMARY KEY (CONNECTION_KEY, FIRMA, LOGO_PERSONEL),
    CONSTRAINT UQ_LUMEN_ACTOR_SCOPE UNIQUE (CONNECTION_KEY, FIRMA, ACTOR_ID)
);
CREATE TABLE dbo.LUMEN_FAVORITES (
    CONNECTION_KEY VARCHAR(64) COLLATE Latin1_General_100_BIN2 NOT NULL,
    FIRMA SMALLINT NOT NULL,
    ACTOR_ID UNIQUEIDENTIFIER NOT NULL,
    FAVORITES VARCHAR(3239) NOT NULL,
    CONSTRAINT PK_LUMEN_FAVORITES PRIMARY KEY (CONNECTION_KEY, FIRMA, ACTOR_ID),
    CONSTRAINT FK_LUMEN_FAVORITES_ACTOR FOREIGN KEY (CONNECTION_KEY, FIRMA, ACTOR_ID)
        REFERENCES dbo.LUMEN_ACTOR_LINK (CONNECTION_KEY, FIRMA, ACTOR_ID)
);
COMMIT;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK;
    THROW;
END CATCH;
-- Runtime grants to a separately created account: SELECT on LUMEN_ACTOR_LINK;
-- SELECT/INSERT/UPDATE on LUMEN_FAVORITES only. No mapping write or DDL grant.
