IF OBJECT_ID('dbo.M_SAYFA_ZIYARET', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.M_SAYFA_ZIYARET (
        LOGICALREF INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PERSONEL_ID INT NOT NULL,
        SAYFA NVARCHAR(260) NOT NULL,
        SAYFA_BASLIK NVARCHAR(160) NOT NULL,
        SAYFA_URL NVARCHAR(400) NOT NULL,
        ZIYARET_SAYISI INT NOT NULL CONSTRAINT DF_M_SAYFA_ZIYARET_SAYI DEFAULT 1,
        ILK_ZIYARET DATETIME NOT NULL CONSTRAINT DF_M_SAYFA_ZIYARET_ILK DEFAULT GETDATE(),
        SON_ZIYARET DATETIME NOT NULL CONSTRAINT DF_M_SAYFA_ZIYARET_SON DEFAULT GETDATE()
    );
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'UX_M_SAYFA_ZIYARET_PERSONEL_SAYFA'
      AND object_id = OBJECT_ID('dbo.M_SAYFA_ZIYARET')
)
BEGIN
    CREATE UNIQUE INDEX UX_M_SAYFA_ZIYARET_PERSONEL_SAYFA
    ON dbo.M_SAYFA_ZIYARET (PERSONEL_ID, SAYFA);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_M_SAYFA_ZIYARET_PERSONEL_SON'
      AND object_id = OBJECT_ID('dbo.M_SAYFA_ZIYARET')
)
BEGIN
    CREATE INDEX IX_M_SAYFA_ZIYARET_PERSONEL_SON
    ON dbo.M_SAYFA_ZIYARET (PERSONEL_ID, SON_ZIYARET DESC);
END;
