-- M_TAHSILAT_LOG — mshop nakit tahsilat (BETA) geri-alma kaydı.
-- Runtime'da tahsilat_lib.php/tahsilat_log_tablo_olustur() guard'lı oluşturur; bu dosya referans.
IF OBJECT_ID('dbo.M_TAHSILAT_LOG','U') IS NULL
CREATE TABLE M_TAHSILAT_LOG (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    REQUEST_ID VARCHAR(40) NOT NULL,
    FIRMADONEM VARCHAR(20) NOT NULL,
    DURUM VARCHAR(20) NOT NULL CONSTRAINT DF_MTL_DURUM DEFAULT 'AKTIF',   -- AKTIF | GERIALINDI | HATA
    TUR VARCHAR(10) NOT NULL CONSTRAINT DF_MTL_TUR2 DEFAULT 'tahsilat',   -- tahsilat | odeme
    KSLINES_REF INT NULL, KSLINES_FICHENO VARCHAR(40) NULL,               -- kasa satırı (giriş=tahsilat / çıkış=ödeme)
    CLFLINE_REF INT NULL, CLFLINE_TRANNO VARCHAR(40) NULL,                -- cari alacak satırı
    CLIENTREF INT NOT NULL, KASAREF INT NOT NULL,
    TUTAR DECIMAL(28,8) NOT NULL CONSTRAINT DF_MTL_TUT DEFAULT 0,
    ACIKLAMA NVARCHAR(255) NULL,
    KULLANICI INT NULL, IP VARCHAR(64) NULL,
    OLUSTURMA DATETIME NOT NULL CONSTRAINT DF_MTL_OLU DEFAULT GETDATE(),
    HATA NVARCHAR(MAX) NULL,
    GERIALAN_KULLANICI INT NULL, GERIALMA DATETIME NULL, GERIALMA_NOT VARCHAR(255) NULL,
    CONSTRAINT UQ_MTL_REQ UNIQUE (REQUEST_ID)
);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_MTL_CARI')  CREATE INDEX IX_MTL_CARI  ON M_TAHSILAT_LOG(CLIENTREF);
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_MTL_DURUM') CREATE INDEX IX_MTL_DURUM ON M_TAHSILAT_LOG(DURUM);
